"""
build_world_view.py — inline WorldForge's JS into index.html.

The packaged pywebview app does not reliably serve sibling static .js files
(they silently 404 at runtime while working fine under a dev http server), so
anything the UI needs must live inside index.html. This mirrors what
generate_icon_cats.py does for the icon data.

Sources, in load order:
    src_web/three.min.js      vendored three.js r149 (UMD, MIT)
    src_web/world_view.js     the editor itself

They live in src_web/ rather than aceforge/web/ on purpose: ACEForge.spec bundles
everything under aceforge/web/ recursively, so a copy left there would ship in
the installer as ~600 KB of dead weight alongside the inlined copy.

Both are replaced between their marker comments, so re-running is idempotent.

    python build_world_view.py            # inject
    python build_world_view.py --check    # report status, change nothing
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
INDEX = ROOT / "aceforge" / "web" / "index.html"
THREE = ROOT / "src_web" / "three.min.js"
WORLD = ROOT / "src_web" / "world_view.js"

BLOCKS = [
    ("WORLDFORGE-VENDOR", THREE, "three.js r149 (vendored, MIT)"),
    ("WORLDFORGE",        WORLD, "WorldForge editor"),
]


def _marker_re(name: str) -> re.Pattern:
    # No DOTALL games: match lazily across lines between the two markers.
    return re.compile(
        rf"(<!-- {name}-START -->)(.*?)(<!-- {name}-END -->)",
        re.S,
    )


def _syntax_check(source: Path) -> str:
    """
    Syntax-check a JS source with node, if node is installed.

    Worth the round-trip: a single bad escape doesn't break one function, it
    stops the whole inlined <script> from parsing, so WorldForge silently
    disappears with no console error to point at. Returns "" when fine, or the
    error text. Skipped (and reported as skipped) when node is unavailable.
    """
    node = shutil.which("node")
    if not node:
        return ""
    try:
        proc = subprocess.run([node, "--check", str(source)],
                              capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError) as e:
        return ""                                  # never block the build on this
    if proc.returncode == 0:
        return ""
    return (proc.stderr or proc.stdout or "syntax error").strip()


def inject(check_only: bool = False) -> int:
    if not INDEX.exists():
        print(f"ERROR: {INDEX} not found")
        return 1

    html = INDEX.read_text(encoding="utf-8")
    original = html
    problems = 0

    for name, source, label in BLOCKS:
        pattern = _marker_re(name)
        if not pattern.search(html):
            print(f"ERROR: markers <!-- {name}-START/END --> not found in index.html")
            problems += 1
            continue
        if not source.exists():
            print(f"ERROR: {source.relative_to(ROOT)} missing — cannot inline {label}")
            problems += 1
            continue

        err = _syntax_check(source)
        if err:
            print(f"ERROR: {source.name} has a syntax error — refusing to inline it:\n"
                  f"{err}")
            problems += 1
            continue

        js = source.read_text(encoding="utf-8")
        # A literal </script> inside the source would close the tag early.
        js = js.replace("</script>", "<\\/script>")
        payload = (f"\n<script>/* {label} — generated by build_world_view.py, "
                   f"edit {source.name} instead */\n{js}\n</script>\n")
        # Callable repl so backslashes in the JS aren't read as group escapes.
        html = pattern.sub(lambda m, p=payload: m.group(1) + p + m.group(3), html)
        size = len(js) / 1024
        print(f"  {'would inline' if check_only else 'inlined'} {label}: "
              f"{size:,.0f} KB from {source.name}")

    if problems:
        return 1
    if check_only:
        print("\ncheck only — index.html not written")
        print(f"index.html would be {len(html)/1024/1024:.2f} MB")
        return 0
    if html == original:
        print("\nno change — index.html already up to date")
        return 0

    INDEX.write_text(html, encoding="utf-8", newline="\n")
    print(f"\nwrote {INDEX.relative_to(ROOT)} ({len(html)/1024/1024:.2f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(inject(check_only="--check" in sys.argv))
