"""
saga_templates.py — SagaForge Deterministic Skeleton Generator

Generates structurally correct WeenieFab scripts and SQL from a Story Bible
JSON object.  All quest flag names, WCIDs, trigger types, and emote structure
come from here — the AI never touches any of it.

The AI's only job is to supply dialogue strings for [PLACEHOLDER] slots.
"""

from __future__ import annotations
import re
from datetime import datetime
from typing import Any

TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _esc(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return str(s).replace("'", "''")


def _q(s: str) -> str:
    return f"'{_esc(s)}'"


# ── Quest flag SQL ────────────────────────────────────────────────────────────

def quest_flags_sql(bible: dict) -> str:
    """
    Generate the quest table SQL for every flag in the Story Bible.
    Fully deterministic — no AI involvement.
    """
    flags = bible.get("quest_flags", [])
    if not flags:
        return ""

    lines = [
        f"/* ===== FILE: {bible.get('title','Saga')} Quest Flags ===== */",
        f"/* Generated by SagaForge — {TIMESTAMP} */",
        "",
    ]

    for f in flags:
        name     = f.get("name", "UnknownFlag")
        qid      = f.get("quest_id", 0)
        delta    = f.get("min_delta", 0)
        solves   = f.get("max_solves", 1)
        msg      = f.get("message", "")
        purpose  = f.get("purpose", "")
        if purpose:
            lines.append(f"/* {purpose} */")
        id_part = f"id = '{qid}' OR " if qid else ""
        lines += [
            f"DELETE FROM quest WHERE {id_part}name = '{_esc(name)}';",
            "",
            "INSERT INTO quest (id, name, min_Delta, max_Solves, message)",
            f"VALUES ('{qid}', '{_esc(name)}', '{delta}', '{solves}', '{_esc(msg)}');",
            "",
        ]

    return "\n".join(lines)


# ── Generator SQL ─────────────────────────────────────────────────────────────

def generator_sql(bible: dict, creature_ref: str) -> str:
    """
    Generate a complete generator weenie SQL for a creature entry.
    Fully deterministic.
    """
    creatures = {c["id"]: c for c in bible.get("creatures", [])}
    c = creatures.get(creature_ref)
    if not c:
        return ""

    wcid         = c["generator_wcid"]
    target_wcid  = c["wcid"]
    name         = c.get("name", "Creature")
    delay        = c.get("respawn_delay", 300.0)
    init_create  = c.get("init_create", 1)
    max_create   = c.get("max_create", 1)
    radius       = c.get("generator_radius", 50.0)
    fname        = f"{wcid} {name} Generator.sql"

    lines = [
        f"/* ===== FILE: {fname} ===== */",
        f"/* Generated by SagaForge — {TIMESTAMP} */",
        "",
        f"DELETE FROM `weenie` WHERE `class_Id` = {wcid};",
        "",
        f"INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)",
        f"VALUES ({wcid}, '{_slug(name)}_generator', 35, '{TIMESTAMP}') /* Generator */;",
        "",
        "INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},  81, {max_create}) /* MaxGeneratedObjects */",
        f"     , ({wcid},  82, {init_create}) /* InitGeneratedObjects */",
        f"     , ({wcid},  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */;",
        "",
        "INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},   1, True ) /* Stuck */",
        f"     , ({wcid},  11, True ) /* IgnoreCollisions */",
        f"     , ({wcid},  18, True ) /* Visibility */;",
        "",
        "INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},  41,  {delay:g}) /* RegenerationInterval */",
        f"     , ({wcid},  43, {radius:g}) /* GeneratorRadius */;",
        "",
        "INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},   1, '{_esc(name)} Generator') /* Name */;",
        "",
        "INSERT INTO `weenie_properties_generator`",
        "  (`object_Id`, `probability`, `weenie_Class_Id`, `delay`, `init_Create`,",
        "   `max_Create`, `when_Create`, `where_Create`, `stack_Size`, `palette_Id`,",
        "   `shade`, `obj_Cell_Id`, `origin_X`, `origin_Y`, `origin_Z`,",
        "   `angles_W`, `angles_X`, `angles_Y`, `angles_Z`)",
        f"VALUES ({wcid}, -1, {target_wcid}, 1, {init_create}, {max_create},",
        f"        1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0)",
        f"/* Generate {name} (x{init_create} up to max {max_create}) */;",
    ]

    return "\n".join(lines)


# ── Quest item SQL ────────────────────────────────────────────────────────────

def quest_item_sql(bible: dict, item_ref: str) -> str:
    """
    Generate a simple quest item (token/key) weenie.
    Deterministic — AI provides name and description via Bible.
    """
    items = {i["id"]: i for i in bible.get("items", [])}
    item = items.get(item_ref)
    if not item:
        return ""

    wcid      = item["wcid"]
    name      = item.get("name", "Quest Item")
    desc      = item.get("description", item.get("purpose", ""))
    stackable = item.get("stackable", False)
    max_stack = item.get("max_stack", 1) if stackable else 1
    fname     = f"{wcid} {name}.sql"

    # Weenie type: 22=Stackable, 6=Generic item
    wtype = 22 if stackable else 6
    wtype_comment = "Stackable" if stackable else "Generic"

    lines = [
        f"/* ===== FILE: {fname} ===== */",
        f"/* Generated by SagaForge — {TIMESTAMP} */",
        "",
        f"DELETE FROM `weenie` WHERE `class_Id` = {wcid};",
        "",
        f"INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)",
        f"VALUES ({wcid}, '{_slug(name)}', {wtype}, '{TIMESTAMP}') /* {wtype_comment} */;",
        "",
        "INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},   1,       128) /* ItemType - Misc */",
        f"     , ({wcid},   5,         5) /* EncumbranceVal */",
        f"     , ({wcid},  16,         1) /* ItemUseable - No */",
        f"     , ({wcid},  19,         0) /* Value */",
    ]

    if stackable:
        lines.append(f"     , ({wcid},  25, {max_stack}) /* MaxStackSize */")
        lines.append(f"     , ({wcid},  26,         1) /* StackSize */")

    lines += [
        f"     , ({wcid},  33,         1) /* Bonded - Bonded */",
        f"     , ({wcid},  35,         1) /* Attuned - Attuned */",
        f"     , ({wcid},  93,      4660) /* PhysicsState */;",
        "",
        "INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},  11, True ) /* IgnoreCollisions */",
        f"     , ({wcid},  13, False) /* Ethereal */",
        f"     , ({wcid},  14, True ) /* GravityStatus */;",
        "",
        "INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},  39,       1) /* DefaultScale */;",
        "",
        "INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},   1, '{_esc(name)}') /* Name */",
    ]

    if desc:
        lines.append(f"     , ({wcid},   2, '{_esc(desc)}') /* ShortDesc */")

    lines[-1] = lines[-1] + ";"  # close the VALUES block

    lines += [
        "",
        "INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)",
        f"VALUES ({wcid},   8, 0x06001036) /* Icon */;",
    ]

    return "\n".join(lines)


# ── NPC WeenieFab skeleton ────────────────────────────────────────────────────

def npc_weeniefab_skeleton(bible: dict, npc_ref: str) -> str:
    """
    Build a complete WeenieFab emote script for an NPC from the Story Bible.

    Structural elements (triggers, flags, WCIDs, flow logic) are written by
    this function deterministically.  Every [PLACEHOLDER] is a slot the AI
    fills with dialogue text — nothing structural.

    Returns the WeenieFab script as a string (not SQL).
    The caller pipes this through _process_emote_scripts() to get SQL.
    """
    npcs     = {n["id"]: n for n in bible.get("npcs", [])}
    items    = {i["id"]: i for i in bible.get("items", [])}
    rewards  = bible.get("rewards", [])
    flow     = bible.get("flow", [])

    npc = npcs.get(npc_ref)
    if not npc:
        return ""

    wcid           = npc["wcid"]
    name           = npc.get("name", "NPC")
    flags          = npc.get("quest_flags", [])
    gives_item_ref = npc.get("gives_item_id")   # id of item this NPC gives
    takes_item_ref = npc.get("takes_item_id")   # id of item this NPC takes
    role           = npc.get("role", "")
    kt_flag        = npc.get("kill_task_flag")  # if NPC checks a kill task

    gives_item = items.get(gives_item_ref) if gives_item_ref else None
    takes_item = items.get(takes_item_ref) if takes_item_ref else None

    # Primary quest flag — first in the list
    primary_flag = flags[0] if flags else None
    done_flag    = flags[1] if len(flags) > 1 else (primary_flag + "Done" if primary_flag else "QuestDone")

    lines = [
        f"-- EMOTE SCRIPT (WCID: {wcid})",
        "",
    ]

    # ── HeartBeat idle animations ─────────────────────────────────────────────
    lines += [
        "HeartBeat:",
        "    - Motion: Twitch1",
        "",
        "HeartBeat:",
        "    - Motion: Twitch2",
        "",
    ]

    # ── Use trigger (player clicks NPC) ──────────────────────────────────────
    lines += ["Use:"]

    if primary_flag:
        # Check if the quest chain is fully complete
        lines += [
            f"    - InqQuest: {done_flag}",
            f"        QuestSuccess:",
            f"            - Tell: [ALREADY_DONE_DIALOGUE]",
            f"        QuestFailure:",
            f"            - Goto: CheckProgress",
            "",
            "GotoSet: CheckProgress",
        ]

        if kt_flag:
            # Check kill task progress before accepting
            lines += [
                f"    - InqQuest: {primary_flag}",
                f"        QuestSuccess:",
                f"            - Goto: CheckKills",
                f"        QuestFailure:",
                f"            - Goto: Intro",
                "",
                "GotoSet: CheckKills",
                f"    - InqQuestSolves: {kt_flag}, 1, 2147483647",
                f"        QuestSuccess:",
                f"            - Goto: RewardPlayer",
                f"        QuestFailure:",
                f"            - Tell: [KILL_PROGRESS_DIALOGUE]",
                "            - DirectBroadcast: You have defeated %tqc out of %tqm.",
            ]
        else:
            lines += [
                f"    - InqQuest: {primary_flag}",
                f"        QuestSuccess:",
                f"            - Goto: Intro",
                f"        QuestFailure:",
                f"            - Goto: Intro",
            ]

    else:
        lines += [
            "    - Tell: [GENERIC_GREETING_DIALOGUE]",
        ]

    lines.append("")

    # ── Intro GotoSet ──────────────────────────────────────────────────────────
    lines += [
        "GotoSet: Intro",
        "    - Motion: Salute",
        "    - Tell: [INTRO_DIALOGUE_LINE_1]",
        "    - Tell: [INTRO_DIALOGUE_LINE_2]",
    ]

    if primary_flag and not kt_flag and not takes_item:
        lines += [
            f"    - StampQuest: {primary_flag}",
        ]

    if gives_item:
        lines += [
            f"    - Give: {gives_item['wcid']}",
            "    - Tell: [ITEM_GIVEN_DIALOGUE]",
        ]

    lines.append("")

    # ── Give trigger (player hands item to NPC) ───────────────────────────────
    if takes_item:
        lines += [
            "Give:",
            f"    - InqOwnsItems: {takes_item['wcid']}, 1",
            f"        TestSuccess:",
            f"            - TakeItems: {takes_item['wcid']}, 1",
            f"            - Goto: RewardPlayer",
            f"        TestFailure:",
            f"            - Tell: [WRONG_ITEM_DIALOGUE]",
            "",
        ]

    # ── RewardPlayer GotoSet ──────────────────────────────────────────────────
    if primary_flag or takes_item or kt_flag:
        lines += [
            "GotoSet: RewardPlayer",
            "    - Motion: Salute",
            "    - Tell: [REWARD_DIALOGUE_LINE_1]",
            "    - Tell: [REWARD_DIALOGUE_LINE_2]",
        ]

        # XP reward
        xp_rewards = [r for r in rewards if r.get("type") == "xp"]
        for r in xp_rewards:
            pct = str(r.get("value", "5%")).replace("%", "")
            lines.append(f"    - AwardLevelProportionalXP: {pct}%")

        # Luminance reward
        lum_rewards = [r for r in rewards if r.get("type") == "luminance"]
        for r in lum_rewards:
            lines.append(f"    - AwardLuminance: {r.get('value', 0)}")

        # Item rewards
        item_rewards = [r for r in rewards if r.get("type") == "item"]
        for r in item_rewards:
            lines.append(f"    - Give: {r.get('wcid', 0)}  /* {r.get('name', 'reward')} */")

        # Stamp completion
        if done_flag:
            lines.append(f"    - StampQuest: {done_flag}")
        if kt_flag:
            lines.append(f"    - EraseQuest: {kt_flag}")

        lines.append("")

    lines.append("-- END EMOTE SCRIPT")
    return "\n".join(lines)


# ── Placeholder inventory ─────────────────────────────────────────────────────

def extract_placeholders(skeleton: str) -> list[str]:
    """
    Return a list of all unique [PLACEHOLDER] names found in a skeleton.
    Used to build the AI dialogue request.
    """
    return list(dict.fromkeys(re.findall(r"\[([A-Z_]+)\]", skeleton)))


# ── Dialogue splice ───────────────────────────────────────────────────────────

def splice_dialogue(skeleton: str, dialogue: dict[str, str]) -> str:
    """
    Replace [PLACEHOLDER] tokens in a skeleton with AI-supplied dialogue strings.
    dialogue = {"INTRO_DIALOGUE_LINE_1": "Hello traveller!", ...}
    Unreplaced placeholders are left as-is so the user can see what's missing.
    """
    result = skeleton
    for key, text in dialogue.items():
        escaped = _esc(text)
        result  = result.replace(f"[{key}]", escaped)
    return result


# ── Bible WCID allocator ──────────────────────────────────────────────────────

def allocate_wcids(bible_draft: dict, config) -> dict:
    """
    Takes a Story Bible draft (from AI, with no WCIDs) and assigns WCIDs
    from config ranges.  Returns the Bible with all wcid fields populated.
    Advances the config 'next' counters so subsequent calls don't collide.
    """
    ranges = config.get_wcid_ranges()

    def _next(range_key: str, fallback_start: int = 800000) -> int:
        r = ranges.setdefault(range_key, {
            "start": fallback_start, "next": fallback_start, "label": range_key
        })
        wcid = r.get("next", r.get("start", fallback_start))
        r["next"] = wcid + 1
        return wcid

    # Assign creature + generator WCIDs
    for c in bible_draft.get("creatures", []):
        c["wcid"]           = _next("campaign_creatures")
        c["generator_wcid"] = _next("campaign_creatures")  # generators live in same range

    # Assign NPC WCIDs
    for n in bible_draft.get("npcs", []):
        n["wcid"] = _next("custom_npcs")

    # Assign item WCIDs
    for i in bible_draft.get("items", []):
        i["wcid"] = _next("custom_items")

    # Assign quest flag IDs (sequential, starting from existing next)
    quest_id_start = ranges.get("kill_tasks", {}).get("next", 1000000)
    for idx, f in enumerate(bible_draft.get("quest_flags", [])):
        f["quest_id"] = quest_id_start + idx
    if bible_draft.get("quest_flags"):
        ranges.setdefault("kill_tasks", {})["next"] = (
            quest_id_start + len(bible_draft["quest_flags"])
        )

    # Build the files list from what's in the Bible
    files = []
    idx   = 0

    for item in bible_draft.get("items", []):
        files.append({
            "index": idx, "wcid": item["wcid"],
            "name":  f"{item['wcid']} {item['name']}.sql",
            "type":  "item", "ref": item["id"],
        })
        idx += 1

    for npc in bible_draft.get("npcs", []):
        files.append({
            "index": idx, "wcid": npc["wcid"],
            "name":  f"{npc['wcid']} {npc['name']}.sql",
            "type":  "npc", "ref": npc["id"],
        })
        idx += 1

    for c in bible_draft.get("creatures", []):
        files.append({
            "index": idx, "wcid": c["wcid"],
            "name":  f"{c['wcid']} {c['name']}.sql",
            "type":  "creature", "ref": c["id"],
        })
        idx += 1
        files.append({
            "index": idx, "wcid": c["generator_wcid"],
            "name":  f"{c['generator_wcid']} {c['name']} Generator.sql",
            "type":  "generator", "ref": c["id"],
        })
        idx += 1

    if bible_draft.get("quest_flags"):
        title = _slug(bible_draft.get("title", "saga"))
        files.append({
            "index": idx,
            "name":  f"{title}_quest_flags.sql",
            "type":  "quests", "ref": "all",
        })

    bible_draft["files"] = files

    # Persist WCID range advances
    config._data["wcid_ranges"] = ranges
    config.save()

    return bible_draft
